# Tensors
is_tensor

is_storage

is_complex

is_conj

is_floating_point

is_nonzero

set_default_dtype

get_default_dtype

set_default_device

get_default_device

numel

set_printoptions


In [2]:
import torch
# 1. is_tensor()判断一个对象是否是张量，需要专门用torch的tensor来创建张量，否则不是张量
# 创建张量
x = torch.tensor([1, 2, 3])
print(torch.is_tensor(x))  # 输出: True

# 非张量
y = [1, 2, 3]
print(torch.is_tensor(y))  # 输出: False


True
False


In [3]:
# is_storage()判断一个对象是否是存储对象，也是需要用torch的tensor来创建张量，然后通过storage()方法来获取存储对象
# 创建张量的存储对象
x = torch.tensor([1, 2, 3])
storage = x.storage()
print(torch.is_storage(storage))  # 输出: True

# 非存储对象
print(torch.is_storage(x))  # 输出: False

True
False


C:\Users\epiph\AppData\Local\Temp\ipykernel_9364\3205632684.py:4: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = x.storage()


In [4]:
#  is_complex()判断一个张量是否是复数类型。
# 复数张量
x = torch.tensor([1 + 1j, 2 + 2j])
print(torch.is_complex(x))  # 输出: True

# 非复数张量
y = torch.tensor([1, 2, 3])
print(torch.is_complex(y))  # 输出: False

True
False


In [5]:
# is_conj()判断张量是否为共轭张量。

x = torch.tensor([1 + 1j, 2 + 2j])
y = x.conj()
print(y.is_conj())  # 输出: True

True


In [6]:
# is_floating_point()判断张量是否为浮点数类型。
x = torch.tensor([1.5, 2.5, 3.5])
print(torch.is_floating_point(x))  # 输出: True

y = torch.tensor([1, 2, 3])
print(torch.is_floating_point(y))  # 输出: False


True
False


In [7]:
# is_nonzero()判断张量是否为非零标量。
# 标量非零值
x = torch.tensor(3)
print(x.is_nonzero())  # 输出: True

# 标量零值
y = torch.tensor(0)
print(y.is_nonzero())  # 输出: False

# 非标量的张量会报错
z = torch.tensor([1, 2, 3])
# z.is_nonzero()  # 会报错

True
False


In [8]:
# is_nonzero()判断张量是否为非零标量，注意这里只能判断
# 标量非零值
x = torch.tensor(3)
print(x.is_nonzero())  # 输出: True

# 标量零值
y = torch.tensor(0)
print(y.is_nonzero())  # 输出: False

# 非标量的张量会报错
z = torch.tensor([1, 2, 3])
# z.is_nonzero()  # 会报错


True
False


In [9]:
# set_default_dtype()设置默认的浮点数数据类型。

torch.set_default_dtype(torch.float64)
x = torch.tensor([1.5, 2.5])
print(x.dtype)  # 输出: torch.float64

# get_default_dtype()获取当前默认的浮点数数据类型。
dtype = torch.get_default_dtype()
print(dtype)  # 输出当前默认的浮点数类型，例如 torch.float64

torch.float64
torch.float64


In [10]:
# set_default_device()设置默认设备（如CPU或GPU）。
torch.set_default_device('cpu')  # 设置默认设备为CPU
x = torch.tensor([1.5, 2.5])
print(x.device)  # 输出: cuda:0


cpu


In [11]:
# numel()返回张量中的元素总数。
x = torch.tensor([[1, 2], [3, 4]])
print(torch.numel(x))  # 输出: 4

4


In [12]:
# set_printoptions()
torch.set_printoptions(precision=3)  # 设置打印精度为3位小数
x = torch.tensor([1.234567, 2.345678])
print(x)  # 输出: tensor([1.235, 2.346])

tensor([1.235, 2.346])


# 创建操作（Creation Ops）

In [13]:
# tensor()创建一个张量，类似于 numpy 中的 array()，但没有自动求导历史。
import torch

x = torch.tensor([[1, 2], [3, 4]])
print(x)
# 输出:
# tensor([[1, 2],
#         [3, 4]])

tensor([[1, 2],
        [3, 4]])


In [14]:
# sparse_coo_tensor()创建一个稀疏 COO 格式的张量，提供值和对应的索引。
values = torch.tensor([1, 2, 3])
indices = torch.tensor([[0, 1, 1], [2, 0, 2]])
sparse_tensor = torch.sparse_coo_tensor(indices, values, [2, 3])
print(sparse_tensor)
# 输出:
# tensor(indices=tensor([[0, 1, 1],
#                        [2, 0, 2]]),
#        values=tensor([1, 2, 3]),
#        size=(2, 3), nnz=3, layout=torch.sparse_coo)


# sparse_csr_tensor()创建一个稀疏 CSR 格式的张量。
crow_indices = torch.tensor([0, 2, 3])
col_indices = torch.tensor([0, 2, 1])
values = torch.tensor([1, 2, 3])
sparse_csr = torch.sparse_csr_tensor(crow_indices, col_indices, values)
print(sparse_csr)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([1, 2, 3]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)
tensor(crow_indices=tensor([0, 2, 3]),
       col_indices=tensor([0, 2, 1]),
       values=tensor([1, 2, 3]), size=(2, 3), nnz=3, layout=torch.sparse_csr)


c:\Users\epiph\.conda\envs\torchproject\Lib\site-packages\torch\utils\_device.py:77: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at ..\aten\src\ATen\SparseCsrTensorImpl.cpp:55.)
  return func(*args, **kwargs)


In [15]:
# asarray()将对象转换为张量。
import numpy as np
import pandas as pd
arr = np.array([1, 2, 3])
# arr = [1, 2, 3]二者都可以转换
# arr2 = pd.Series([1, 2, 3]) pandas 的Series对象也可以转换
x = torch.asarray(arr)
print(x)  # 输出: tensor([1, 2, 3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)


In [16]:
# as_tensor()与 tensor() 类似，但它共享数据并保留自动求导历史。
import numpy as np

arr = np.array([1, 2, 3])
x = torch.as_tensor(arr)
print(x)  # 输出: tensor([1, 2, 3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)


In [17]:
# from_numpy()从 numpy 数组创建张量。
arr = np.array([1.0, 2.0, 3.0])
x = torch.from_numpy(arr)
print(x)  # 输出: tensor([1., 2., 3.], dtype=torch.float64)

tensor([1., 2., 3.])


In [18]:
# zeros()创建一个全为 0 的张量。
x = torch.zeros(2, 3)
print(x)
# 输出:
# tensor([[0., 0., 0.],
#         [0., 0., 0.]])


# ones()创建一个全为 1 的张量。
x = torch.ones(2, 3)
print(x)
# 输出:
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
# arange()创建一个从 start 到 end（不包含 end）的张量，间隔为 step。
x = torch.arange(0, 10, 2) # 从0开始，步长为2，到10结束（不包含10）
print(x)  #    输出: tensor([0, 2, 4, 6, 8])


# linspace()创建一个包含 steps 个均匀间隔的数值的张量，范围从 start 到 end。
x = torch.linspace(0, 1, steps=5) # steps代表步长，也就是张量元素数量
print(x)  # 输出: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

tensor([0, 2, 4, 6, 8])
tensor([0.000, 0.250, 0.500, 0.750, 1.000])


In [20]:
# eye()创建一个对角线为 1 的单位矩阵。
x = torch.eye(3)
print(x)
# 输出:
# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]])

# empty()创建一个未初始化的数据张量。
x = torch.empty(2, 3)
print(x)  # 输出: 未初始化的随机数据，无限接近0，小概率不为0

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [21]:
# full()创建一个大小为 size 的张量，并用 fill_value 填充。
x = torch.full((2, 3), 7) # (2, 3)代表张量大小，7代表填充值，这里只能填充相同的数
print(x)
# 输出:
# tensor([[7, 7, 7],
#         [7, 7, 7]])

tensor([[7, 7, 7],
        [7, 7, 7]])


In [22]:
# complex()构造一个复数张量。
real = torch.tensor([1.0, 2.0])
imag = torch.tensor([3.0, 4.0])
z = torch.complex(real, imag)
print(z)
# 输出: tensor([1.+3.j, 2.+4.j])


tensor([1.+3.j, 2.+4.j])


In [23]:
# polar()使用极坐标创建复数张量。
abs_values = torch.tensor([1.0, 2.0])
angles = torch.tensor([3.1416/2, 3.1416])
z = torch.polar(abs_values, angles)
print(z)
# 输出: tensor([6.1232e-17+1.0000j, -2.0000+0.0000j])

tensor([-3.673e-06+1.000e+00j, -2.000e+00-1.469e-05j])


# Indexing, Slicing, Joining, Mutating Ops

In [24]:
# adjoint()返回一个张量的共轭转置（只作用于最后两个维度）。
x = torch.tensor([[1 + 1j, 2 + 2j], [3 + 3j, 4 + 4j]])
adjoint_x = x.adjoint()
print(adjoint_x)
# 输出: 
# tensor([[1.-1.j, 3.-3.j],
#         [2.-2.j, 4.-4.j]])

tensor([[1.-1.j, 3.-3.j],
        [2.-2.j, 4.-4.j]])


In [25]:
# argwhere()返回张量中所有非零元素的索引。
x = torch.tensor([[1, 0], [2, 3]])
indices = torch.argwhere(x)
print(indices)
# 输出: 
# tensor([[0, 0],
#         [1, 0],
#         [1, 1]])

tensor([[0, 0],
        [1, 0],
        [1, 1]])


In [26]:
# cat()将张量沿指定维度连接。
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y), dim=0) # dim=0代表按行连接
print(z)
# 输出: 
# tensor([[1, 2],
#         [3, 4],
#         [5, 6],
#         [7, 8]])
z = torch.cat((x, y), dim=1) # dim=1代表按列连接
print(z)


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [27]:
# chunk()将张量分割为指定数量的块。
x = torch.tensor([1, 2, 3, 4, 5, 6])
chunks = torch.chunk(x, 3)
for c in chunks:
    print(c)
# 输出: 
# tensor([1, 2])
# tensor([3, 4])
# tensor([5, 6])

print(chunks)

tensor([1, 2])
tensor([3, 4])
tensor([5, 6])
(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))


In [28]:
# gather()根据索引从张量中收集值。
x = torch.tensor([[1, 2], [3, 4]])
index = torch.tensor([[0, 0, 1], [1, 0, 1]])
output = torch.gather(x, dim=1, index=index) # dim=1代表按列收集，index代表索引，前面的0，0代表选取两次第一行第一列，后面的1，0代表选取第二行第二列和第二行第一列
# dim=1表示按列收集，所以第一个[]表示收集第一列，第二个[]表示收集第二列，中间的数字代表具体在这一列取的值

print(output)
# 输出: 
# tensor([[1, 1, 2],
#         [4, 3, 4]])

index = torch.tensor([[1, 1], [1, 0]])
output = torch.gather(x, dim=0, index=index) # dim=0
# dim=0表示按行收集，所以第两个[]的第一个数表示收集第一列，两个[]的第二个数表示手机第二列

print(output)

tensor([[1, 1, 2],
        [4, 3, 4]])
tensor([[3, 4],
        [3, 2]])


In [29]:
# index_select()根据索引选择张量的某一维度。
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
indices = torch.tensor([0, 2])
output = torch.index_select(x, dim=0, index=indices) # dim为0代表找最外层的维度的元素，通常来说dim数值越小，代表越外层的维度，中间取出来的元素也会更大
print(output)
# 输出: 
# tensor([[1, 2],
#         [5, 6]])

indices = torch.tensor([0, 1])
output = torch.index_select(x, dim=1, index=indices) # dim为1代表第二外层的元素，在这里就是内层的，只有两个元素，index不可以超过1
print(output)

tensor([[1, 2],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [30]:
# masked_select()根据布尔掩码选择张量中的元素。
x = torch.tensor([1, 2, 3, 4])
mask = torch.tensor([0, 1, 0, 1], dtype=torch.bool)
output = torch.masked_select(x, mask) # 模型mask操作步骤非常常用，一般来说首先创建含有随机数量0的张量，对应过程张量，然后相乘，达到mask效果，维度不会改变，但是长度会改变
print(output)
# 输出: tensor([2, 4])



tensor([2, 4])


In [31]:
# narrow()返回一个张量的指定维度上的窄视图。

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
narrow_x = torch.narrow(x, dim=1, start=1, length=2) # 从dim=1开始，取2个元素，且起始位置是第1号位
print(narrow_x)
# 输出: 
# tensor([[2, 3],
#         [5, 6]])

tensor([[2, 3],
        [5, 6]])


In [32]:
# permute()返回一个张量的维度重新排列后的视图。
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
perm_x = x.permute(1, 0) # 将第一维和第二维交换，相当于转置
print(perm_x)
# 输出: 
# tensor([[1, 4],
#         [2, 5],
#         [3, 6]])

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [33]:
# reshape()返回具有相同数据但形状不同的张量。

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_x = x.reshape(3, 2) # 从左到右，先看最外层，再往里看，最外层是3，内层是2，所以先取3个元素，每个元素有2个元素，所以取3*2个元素
print(reshaped_x)
# 输出: 
# tensor([[1, 2],
#         [3, 4],
#         [5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [34]:
# squeeze()移除大小为1的指定维度。
x = torch.tensor([[[1], [2], [3]]]) # 将外层的维度去掉，只保留最内层维度
squeezed_x = torch.squeeze(x)
print(squeezed_x)
# 输出: tensor([1, 2, 3])

x = torch.tensor([[[1,1], [2,1], [3,1]]]) # 将外层的维度去掉，只保留最内层维度，但是最内层维度有两个，所以保留两个维度，不能破坏数据本身的结构
squeezed_x = torch.squeeze(x)
print(squeezed_x)


tensor([1, 2, 3])
tensor([[1, 1],
        [2, 1],
        [3, 1]])


In [38]:
# stack()沿着新维度连接张量。
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
stacked = torch.stack((x, y), dim=0)
print(stacked)
# 输出: 
# tensor([[1, 2],
#         [3, 4]])
stacked = torch.stack((x, y), dim=1)
print(stacked)


tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])


In [42]:
# transpose()返回转置后的张量。
x = torch.tensor([[1, 2], [3, 4]])
transposed_x = torch.transpose(x, 0, 1)# 将第一维和第二维交换，相当于转置，0，1和1，0效果一样
print(transposed_x)
# 输出: 
# tensor([[1, 3],
#         [2, 4]])

tensor([[1, 3],
        [2, 4]])


In [48]:
# unsqueeze()在指定位置插入一个大小为1的新维度。
x = torch.tensor([1, 2, 3])
unsqueezed_x = torch.unsqueeze(x, dim=0)
print(unsqueezed_x)
# 输出: 
# tensor([[1, 2, 3]])

unsqueezed_x = torch.unsqueeze(x, dim=1)
print(unsqueezed_x)


tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])


In [49]:
# where()根据条件选择元素。
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
condition = torch.tensor([True, False, True]) # 这里的condition待会作用于x和y，如果为True，则取x的值，否则取y的值
output = torch.where(condition, x, y)
print(output)
# 输出: tensor([1, 5, 3])


tensor([1, 5, 3])


# Generator
在 PyTorch 中，Generator 用于创建和管理随机数生成器对象，该对象可以控制随机数生成算法的状态。通过使用 Generator，你可以更精确地控制伪随机数生成器的种子和行为，这在需要可重复实验结果时非常有用。

主要用途
通过指定种子来生成确定性的伪随机数序列。
可以在不同的设备（如 CPU 或 GPU）上管理随机数生成状态。
创建 Generator 对象的实例
你可以通过 torch.Generator() 来创建生成器，并使用 generator.manual_seed() 方法为其设定种子。

In [50]:
import torch

# 创建一个 Generator 对象
gen = torch.Generator()

# 手动设置种子，确保生成相同的随机数序列
gen.manual_seed(42)

# 使用该生成器生成随机数
random_tensor = torch.rand(3, generator=gen)
print(random_tensor)

# 再次生成随机数，因种子相同，所以结果相同
random_tensor2 = torch.rand(3, generator=gen)
print(random_tensor2)

# 生成器的状态保存在 `gen` 中，可以随时修改或查询


tensor([0.058, 0.063, 0.124])
tensor([0.053, 0.526, 0.477])


# Random sampling

In [51]:
# seed()
# seed() 方法为所有设备（如 CPU 和 GPU）的随机数生成器设置一个非确定性（随机的）种子。
# 这意味着每次调用时会生成一个不同的随机种子，适用于希望每次执行代码时生成不同随机数的情况。
torch.seed()  # 设置一个随机种子

# manual_seed(seed) 用于在所有设备上手动设置一个确定的随机数种子。

torch.manual_seed(42)  # 设置一个固定的随机数种子

# 生成随机张量
random_tensor = torch.rand(3)
print(random_tensor)

tensor([0.058, 0.063, 0.124])


In [52]:
# get_rng_state() 返回当前设备上随机数生成器的状态，通常以 torch.ByteTensor 的形式表示。
# 你可以通过保存这个状态来确保随后的随机数生成能够恢复到当前状态。
rng_state = torch.get_rng_state()
print(rng_state)  # 打印当前随机数生成器状态

tensor([42,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)


In [53]:
# set_rng_state(state) 用于设置设备上随机数生成器的状态。
# 你可以通过先使用 get_rng_state() 保存状态，再使用 set_rng_state() 恢复到之前的状态，确保随机数生成的顺序不被打乱。
# 保存当前随机数生成器状态
rng_state = torch.get_rng_state()

# 生成一个随机张量
random_tensor = torch.rand(3)
print(random_tensor)

# 恢复随机数生成器状态
torch.set_rng_state(rng_state)

# 再次生成随机张量，应该与之前相同
random_tensor = torch.rand(3)
print(random_tensor)


tensor([0.053, 0.526, 0.477])
tensor([0.053, 0.526, 0.477])
