## 图的表示（邻接矩阵表示图）
图可以通过稀疏矩阵表示，通常使用邻接矩阵来表示图中的节点和边。

In [5]:
from scipy.sparse import csr_matrix
import numpy as np

# 创建一个图的邻接矩阵
graph = np.array([[0, 1, 0, 0, 0, 0],
                  [1, 0, 1, 0, 0, 0],
                  [0, 1, 0, 1, 1, 0],
                  [0, 0, 1, 0, 0, 1],
                  [0, 0, 1, 0, 0, 1],
                  [0, 0, 0, 1, 1, 0]])

# 将邻接矩阵转换为稀疏矩阵
graph_sparse = csr_matrix(graph)
print("Graph in Sparse Format:\n", graph_sparse)


Graph in Sparse Format:
   (0, 1)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	1
  (3, 2)	1
  (3, 5)	1
  (4, 2)	1
  (4, 5)	1
  (5, 3)	1
  (5, 4)	1


## 最短路径算法
### shortest_path
shortest_path 计算图中所有节点之间的最短路径，支持多种算法，包括 Dijkstra、Floyd-Warshall 等。

In [6]:
from scipy.sparse.csgraph import shortest_path

# 计算最短路径
dist_matrix, predecessors = shortest_path(graph_sparse, return_predecessors=True, method='auto', directed=False)
print("Shortest Path Distance Matrix:\n", dist_matrix)
print("Predecessors:\n", predecessors)


Shortest Path Distance Matrix:
 [[0. 1. 2. 3. 3. 4.]
 [1. 0. 1. 2. 2. 3.]
 [2. 1. 0. 1. 1. 2.]
 [3. 2. 1. 0. 2. 1.]
 [3. 2. 1. 2. 0. 1.]
 [4. 3. 2. 1. 1. 0.]]
Predecessors:
 [[-9999     0     1     2     2     3]
 [    1 -9999     1     2     2     3]
 [    1     2 -9999     2     2     3]
 [    1     2     3 -9999     2     3]
 [    1     2     4     2 -9999     4]
 [    1     2     3     5     5 -9999]]


### dijkstra
dijkstra 算法是计算单源最短路径问题的经典算法。

In [7]:
from scipy.sparse.csgraph import dijkstra

# 计算从源节点0出发到所有其他节点的最短路径
distances, predecessors = dijkstra(graph_sparse, return_predecessors=True, indices=0, directed=False)
print("Dijkstra Shortest Path Distances:\n", distances)
print("Dijkstra Predecessors:\n", predecessors)


Dijkstra Shortest Path Distances:
 [0. 1. 2. 3. 3. 4.]
Dijkstra Predecessors:
 [-9999     0     1     2     2     3]


### floyd_warshall
floyd_warshall 是一种全源最短路径算法，适用于计算任意两点之间的最短路径。

In [8]:
from scipy.sparse.csgraph import floyd_warshall

# 计算所有节点之间的最短路径
dist_matrix = floyd_warshall(graph_sparse, directed=False)
print("Floyd-Warshall Shortest Path Distance Matrix:\n", dist_matrix)


Floyd-Warshall Shortest Path Distance Matrix:
 [[0. 1. 2. 3. 3. 4.]
 [1. 0. 1. 2. 2. 3.]
 [2. 1. 0. 1. 1. 2.]
 [3. 2. 1. 0. 2. 1.]
 [3. 2. 1. 2. 0. 1.]
 [4. 3. 2. 1. 1. 0.]]


### bellman_ford
bellman_ford 算法计算单源最短路径，并且可以处理边权为负的图。

In [9]:
from scipy.sparse.csgraph import bellman_ford

# 计算从源节点0出发的最短路径
distances, predecessors = bellman_ford(graph_sparse, return_predecessors=True, indices=0, directed=False)
print("Bellman-Ford Shortest Path Distances:\n", distances)
print("Bellman-Ford Predecessors:\n", predecessors)


Bellman-Ford Shortest Path Distances:
 [0. 1. 2. 3. 3. 4.]
Bellman-Ford Predecessors:
 [-9999     0     1     2     2     3]


## 最小生成树
### minimum_spanning_tree
计算一个图的最小生成树，返回一个稀疏矩阵表示的树。

In [10]:
from scipy.sparse.csgraph import minimum_spanning_tree

# 计算最小生成树
mst = minimum_spanning_tree(graph_sparse)
print("Minimum Spanning Tree:\n", mst.toarray())


Minimum Spanning Tree:
 [[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### kruskal
kruskal 算法是另一种用于计算最小生成树的算法，特别适用于稀疏图。

In [12]:
# from scipy.sparse.csgraph import kruskal

# # 计算最小生成树
# mst_kruskal = kruskal(graph_sparse)
# print("Kruskal's Minimum Spanning Tree:\n", mst_kruskal.toarray())

import networkx as nx

# 创建图
G = nx.Graph()

# 添加带权重的边
G.add_edges_from([(0, 1, {'weight': 1}),
                  (1, 2, {'weight': 2}),
                  (2, 3, {'weight': 1}),
                  (0, 4, {'weight': 3}),
                  (4, 5, {'weight': 1}),
                  (2, 5, {'weight': 2})])

# 使用 Kruskal 算法计算最小生成树
mst_kruskal = nx.minimum_spanning_tree(G, algorithm='kruskal')

# 显示最小生成树的边
print("Kruskal's Minimum Spanning Tree edges:", mst_kruskal.edges(data=True))



Kruskal's Minimum Spanning Tree edges: [(0, 1, {'weight': 1}), (1, 2, {'weight': 2}), (2, 3, {'weight': 1}), (2, 5, {'weight': 2}), (4, 5, {'weight': 1})]


## 连通分量分析
### connected_components
计算图的连通分量，即将图中的节点划分为若干个连通子图。

In [13]:
from scipy.sparse.csgraph import connected_components

# 计算连通分量
n_components, labels = connected_components(graph_sparse, directed=False)
print("Number of connected components:", n_components)
print("Labels for connected components:", labels)


Number of connected components: 1
Labels for connected components: [0 0 0 0 0 0]




### **总结**

| **算法**                | **方法**                    | **描述**                                                      |
|------------------------|----------------------------|--------------------------------------------------------------|
| **图的表示**             | `csr_matrix`               | 使用稀疏矩阵（CSR 格式）表示图的邻接矩阵。                            |
| **最短路径算法**          | `shortest_path`            | 计算所有节点之间的最短路径，支持 Dijkstra、Floyd-Warshall 等。     |
| **最短路径算法**          | `dijkstra`                 | 计算单源最短路径，经典的 Dijkstra 算法。                              |
| **最短路径算法**          | `floyd_warshall`           | 计算全源最短路径，Floyd-Warshall 算法。                              |
| **最短路径算法**          | `bellman_ford`             | 计算单源最短路径，可以处理负权边。                                     |
| **最小生成树**            | `minimum_spanning_tree`    | 使用 Prim 算法计算图的最小生成树。                                    |
| **最小生成树**            | `kruskal`                  | 使用 Kruskal 算法计算图的最小生成树，适用于稀疏图。                   |
| **连通分量分析**          | `connected_components`     | 计算图的连通分量，返回分量数和节点标签。                             |

