## 将python元素转换成numpy元素
有一维，二维，三维数组之分

In [1]:
import numpy as np
a1D = np.array([1, 2, 3, 4]) 
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])



这里如果你要设置存放数据的大小，则不能超出限制，比如int8，前面的数就不能大于127

In [ ]:
#np.array([127, 128, 129], dtype=np.int8)
#会报错

# 自动创建数组
使用arange函数，linspace函数

In [4]:
import numpy as np
print(np.arange(10))# 创建一个从0到9的数组

print(np.arange(2, 10, dtype=float))#设置数据形式为浮点数

print(np.arange(2,3,0.1)) # 设置步长为0.1

print(np.linspace(2.,6.,10)) # 设置2到6之间有10个数的数组，且步长一致



[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
[2.         2.44444444 2.88888889 3.33333333 3.77777778 4.22222222
 4.66666667 5.11111111 5.55555556 6.        ]


# 创建2D数组
e.g. numpy.eye, numpy.diag, and numpy.vander
numpy.eye生成identity matrix
diag可对identity matrix中的1进行赋值
vander输出范德蒙矩阵

In [5]:
import numpy as np
print(np.eye(3))#只有一个参数的时候默认行=列=该数
print(np.eye(4,3))# 4为行数，3为列数


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [8]:
import numpy as np
np.diag([1, 2, 3])#将identity matrix中的1换成1，2，3

np.diag([1, 2, 3], 2)# 将identity matrix中的1换成1，2，3，之后再向左拓展列表大小

a = np.array([[1, 2], [3, 4]])
np.diag(a)


array([1, 4])

In [9]:
x = np.array([1, 2, 3, 4])
V = np.vander(x, 4)
print(V)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


# 三种创建空数组的方式
np.zeros;np.ones;numpy.random库（这里要提前声明）from numpy.random import default_rng
注意这里的np.zeros/ones()中应该填一个数字，代表行和列，==或者填具体的行和列的值（一定要多加一个括号）==

In [13]:
import numpy as np
print(np.zeros((2, 3)))
print(np.ones((3,3)))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
from numpy.random import default_rng
print(default_rng(42).random((2,3))) # 前面的42为种子

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


# numpy.indices用于生成一个表示网格的数组索引，它返回一个包含各个维度坐标的数组。
numpy.indices(dimensions, dtype=int, sparse=False)

In [22]:
import numpy as np

grid = np.indices((2, 3))
print(grid)

# 其中grid的第一个部分列表为第一维度（行）的索引数组，表示行索引（0, 1）
# 其中grid的第二个部分列表为第二维度（列）的索引数组，表示行索引（0, 1，2）
# 代表第几行，第几列

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


# Replicating, joining, or mutating existing arrays

In [28]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2] # 这里默认是[0:2]，则代表的是0，1，也就是前两位
b += 1
print('a =', a, '; b =', b)
# 这里的a也被改变了，因为这个本质上来说在内存中是同一个位置，如果要将a，b分开来，则用numpy.copy

a = [2 3 3 4 5 6] ; b = [2 3]


In [30]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a[:2].copy() # 这里才是将一个新的数组先分配给了b，而不是和a共用同一个内存数组
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [3]:
import numpy as np
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])# block 函数用于将数列进行拼接合并

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])