# Single element indexing


In [9]:
import numpy as np
x = np.arange(10)
print(x)
print(x[2])
print(x[-2])

[0 1 2 3 4 5 6 7 8 9]
2
8


### x.shape
x.shape代表x的维度，在改变之前，假设我们x为一个1×10的一维数组，如果我们要把它改变成别的维度数组，我们就会用.shape方法，这里括号内的第一个数字是维度1的值，后面第二个数字则是维度2的值，这里要注意的是，通常来说每一个维度又会被当成一个新的列表，这里就不是原来的元素了
shape内有三个元素则代表是3维度，则代表有三个列表嵌套


In [14]:
x.shape = (10, 1)  # now x is 2-dimensional
x.shape = (2,5)  # now x is 2-dimensional

print(x)
# x[1, 3]
x[0][2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


2

# Slicing and striding
Basic slicing occurs when obj is a slice object (constructed by start:stop:step notation inside of brackets)

In [17]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]# 这里的第一位数1就是起始的index，中间的7代表的是终止的index（但是不包括本身）

array([1, 3, 5])

In [21]:
print(x[-2:10]) # 这里代表的是从8到9，虽然在index索引上好像包括了一整个列表，但是只会从起始的数字到结束的数字
print(x[-2:8]) #当索引从8到7时，输出的就是空列表
x[-3:3:-1] # 不print的话输出还要包括元素的数据类型array。

[8 9]
[]


array([7, 6, 5, 4])

In [22]:
x[5:] #冒号后无数字默认到结尾


array([5, 6, 7, 8, 9])

In [25]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x.shape)# 这里的2代表是最外部的中括号内的元素有2个，3代表是中间层的中括号内部有3个元素，最后的1代表是最里面的中括号内部只有一个元素
x[1:3] # 当冒号后面的索引数大于最大的索引时，只会到最大的索引

(2, 3, 1)


array([[[4],
        [5],
        [6]]])

# dimensional indexing tools
使用 Ellipsis
假设我们想要选择数组 x 的最后一个维度的所有元素，但保留前两个维度的全部信息。可以使用 x[..., 0]，这是 Ellipsis 的一个常见用法：

In [1]:
import numpy as np

x = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[7, 8, 9],
               [10, 11, 12]]])

result = x[..., 0] # 这里的...代表省略的维度，这里的 ... 代表剩余的所有维度，后面的0代表其最后一个维度的第一个数字
print(result)

[[ 1  4]
 [ 7 10]]


# np.newaxis
np.newaxis 或 None 会在数组的索引操作中增加一个新的维度，其长度为1。这个新的维度插入的位置取决于 np.newaxis 或 None 在索引元组中的位置。

In [2]:
import numpy as np

x = np.array([[[1], [2], [3]],
              [[4], [5], [6]]])

print(x.shape)  # 输出: (2, 3, 1)

print(x[:, np.newaxis, :, :].shape)# 其newaxis元素在第二个位置，则新的维度（1）则在第二个位置

print(x[None,:,:,:].shape)# None 在第一个位置，则新的维度在第一个位置

(2, 3, 1)
(2, 1, 3, 1)
(1, 2, 3, 1)


In [8]:
x = np.arange(5)
print(x[:, np.newaxis])
print(x[np.newaxis, :])
print(x[:, np.newaxis]+x[np.newaxis, :])

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


# advanced array indexing 


In [11]:
x = np.arange(10, 1, -1)
print(x)

print(x[np.array([3, 3, 1, 8])])# 这里将需要提出的所有数据的index变成列表的形式，放到x[]中，则数据将会以列表index的形式提取出来

print(x[np.array([3, 3, -3, 8])])

[10  9  8  7  6  5  4  3  2]
[7 7 9 2]
[7 7 4 2]


In [13]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x[np.array([1, -1])] #取1 index和0 index

# x[np.array([3, 4])] # 不可超出范围

array([[3, 4],
       [5, 6]])

In [18]:
y = np.arange(35).reshape(5, 7)
print(y)
y[np.array([1, 2, 4]), np.array([1, 1, 2])] # 相当于是要取出三个位置的数，分别是（1，1），（2，1）和（4，2）
# y[np.array([0, 2, 4]), np.array([0, 1])]当shape不匹配时，会报错

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([ 8, 15, 30])

In [19]:
y = np.arange(35).reshape(5, 7)
y[np.array([0, 2, 4]), 1] # 这里相当于是将（0，1），（2，1）和（4，1）的数取出

array([ 1, 15, 29])

In [20]:
y = np.arange(35).reshape(5, 7)
y[np.array([0, 2, 4])] # 当只有一个索引时，从最大的维度开始取，代表第0行，第2行和第4行

array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

# Combining Advanced and basic indexing

In [2]:
import numpy as np
y = np.arange(35).reshape(5,7)
print(y[np.array([0, 2, 4]), 1:3])
print(y[:, 1:3][np.array([0, 2, 4]), :])
# 二者的效果是一样的，前面是代表第0，2，4行的第1号数和第3号数



[[ 1  2]
 [15 16]
 [29 30]]
[[ 1  2]
 [15 16]
 [29 30]]


In [7]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
print(x[1:3, 1:3])

print(x[1:2, [1, 2]])


[[4 5]
 [7 8]]
[[4 5]]


# Assigning values to indexed arrays

In [11]:
x = np.arange(10)
x[2:7] = 1
x[2:7] = np.arange(5)
x

array([0, 1, 0, 1, 2, 3, 4, 7, 8, 9])